apiVersion: v1
data:
  secretkey: TzM5UjNCVHVieGpLcjNsUUtabG5wbjVBWW0zT0wxcjZrUWRDeGx3VmJKQnVyT3h1RElHYkJEM1JqSVo2K1FUQQpMUFhWc1E1TWYxbVREbGl3d0E5ODFFSUlSb1lKRk9BZnBzaEVZVlZyNlZCdEcyekpxT2JPQjhwbzhBQ2MwclF6CnQ1cjg2RU1Sb2lXQXdOS1RPc2YvU1RseEMydTBTaWhnajdPSjhjb1k3Szg9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
